---
pg_user: "postgres"
pg_password: "mandarynka"
pgadmin_setup_email: "admin@example.com"
pgadmin_setup_password: "mandarynka"
distrib_codename: "noble"

postgresql_packages:
  - curl
  - ca-certificates
  - gnupg
  - lsb-release
  - postgresql
  - postgresql-contrib
  - postgresql-client

pgadmin_packages:
  - pgadmin4-web
  - pgadmin4
